# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92694b43a4f2e76cf3d657ed545c36bf65998dadb170f8ea8d160aba6dfcc143d61040ad4a5b4caafc6b708f0300a6a013665b30cc377809cdf1d5803a0945c6

test:
  secret_key_base: bea6e9fb7122af8b2d0372eebe4b895e343cf9037ffe079d076c0141bdaa558561013e5d466648bdb2c1b2ed4c664ba36f28b1e5f7d8b2d52d698903478ddb3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
